FROM tensorflow/tensorflow

RUN apt-get update
RUN apt-get install -y python3-dev python3-pip
#RUN pip3 install --user --upgrade tensorflow
RUN pip3 install pillow
RUN apt-get install -y curl
RUN apt-get install sudo

#installing nodejs
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs


WORKDIR /toefx-server

COPY package.json ./
COPY package-lock.json ./

# install the node modules
RUN npm install --silent

# copy the code into the container
COPY . /toefx-server

EXPOSE 3001

CMD [ "npm", "start" ]