FROM node:13-alpine as build

WORKDIR /toefx-client

COPY package.json ./
COPY package-lock.json ./

# install the node modules
RUN npm install --silent

# copy the code into the container
COPY . /toefx-client

#RUN npm run build

#FROM nginx:stable-alpine
#COPY --from=build /toefx-client/build /usr/share/nginx/html

#COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf


CMD [ "npm", "start" ]